### ISSUE TITLE
Update/Upgrade to Freedesktop 18.08

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.freedesktop.Sdk.Extension.mono5#2]
flathub/org.freedesktop.Sdk.Extension.gcc8#3
flathub/org.freedesktop.Sdk.Extension.openjdk10#5

Thanks!

**Comment by TingPing** [comment]
https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/commit/e5ce155118621652eda4d8270d50e1fe334eb9c3

**Comment by TingPing** [comment]
Actually the buildbot isn't set up to build that branch yet, I thought that had changed so I'll reopen until then.

**Comment by bilelmoussaoui** [comment]
Any news about this? It's required by Builder here https://gitlab.gnome.org/GNOME/gnome-builder/issues/719

**Comment by TingPing** [comment]
https://flathub.org/builds/#/builders/2/builds/6366

**Comment by TingPing** [comment]
Ugh, ofc triggering a build didn't publish it, probably need to make an empty commit or something.

**Comment by TingPing** [comment]
Ok this has finally been published.
