### ISSUE TITLE
Create branch for runtime 1.6 and/or 18.08

### ISSUE THREAD

**Issue by Unrud** [flathub/org.freedesktop.Sdk.Extension.mono5#5]
Allow support for the runtime 18.08 (https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/pull/4#issuecomment-430036038)

**Comment by TingPing** [comment]
https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/commit/e5ce155118621652eda4d8270d50e1fe334eb9c3
