### ISSUE TITLE
Create branch for runtime 19.08

### ISSUE THREAD

**Issue by Unrud** [flathub/org.freedesktop.Sdk.Extension.mono5#7]
Required for updating https://github.com/flathub/net.openra.OpenRA/ to runtime 19.08.

**Comment by ricvelozo** [comment]
Required to enable Mono module in [org.godotengine.Godot#8](https://github.com/flathub/org.godotengine.Godot/issues/8).

**Comment by Elektron72** [comment]
Required to easily be able to use Mono with the Visual Studio Code flatpak (e.g. with Unity).

**Comment by FakeShemp** [comment]
[com.jetbrains.Rider](https://github.com/flathub/com.jetbrains.Rider) would also need a 19.08 branch to build apps with Mono.

**Comment by nedrichards** [comment]
Some work is being done https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/commits/branch/19.08 but I suspect patches welcome.
